//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointments()
        {
            this.Complaints = new HashSet<Complaints>();
            this.OralCavity = new HashSet<OralCavity>();
        }
    
        public int IdAppointment { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> IdParrentAppointments { get; set; }
        public string ReferralText { get; set; }
        public int IdPatient { get; set; }
        public int IdDoctor { get; set; }
        public string Diagnosis { get; set; }
        public string DevelopmentRealDisease { get; set; }
        public string ObjectiveResearchData { get; set; }
        public string Bite { get; set; }
        public string ConditionCavity { get; set; }
        public string DataXrayStudies { get; set; }
        public string Treatment { get; set; }
        public string TreatmentResults { get; set; }
        public string Instructions { get; set; }
        public Nullable<int> IdheadsDepartment { get; set; }
    
        public virtual Specialistes Specialistes { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaints> Complaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OralCavity> OralCavity { get; set; }
    }
}
