//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        public int IdComplaint { get; set; }
        public int IdAppointment { get; set; }
        public string DescriptionComplaint { get; set; }
    
        public virtual Appointments Appointments { get; set; }
    }
}
