//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diseases
    {
        public int IdDisease { get; set; }
        public string DescriptionDisease { get; set; }
        public int IdUser { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
