//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OralCavity
    {
        public int IdOralCavity { get; set; }
        public int AppointmentsId { get; set; }
        public int Number { get; set; }
        public string Value { get; set; }
    
        public virtual Appointments Appointments { get; set; }
    }
}
